create table CM_INS(CM_ID number(4) primary key,CM_NAME varchar(30),CM_DEPARTMENT varchar(30));
commit;
create table MO_LAW(CLAU_NO number(9) primary key,CLAU_AMD varchar(4),AMD_DATE date());
commit;
create table ACCOMODATION(ACCOD_ID number(9) primary key,ACCOD_HOUSE varchar(30),ACCOD_STREET varchar(30),ACCOD_AREA varchar(30),ACCOD_CITY varchar(30),ACCOD_TYPE varchar(30));
commit;
create table MO_AGRICULTURE(EMP_ID number(9) primary key,EMP_NAME varchar(4),EMD_GRADE number(2),EMP_CHILDREN number(2),EMP_CONTACT number(15));
commit;
create table MO_FINANCE(BPS number(2) primary key,PAY_BONUS number(10),PAY_TEX number(10));
commit;
create table ZAKAT(ZAKAT_ID number(9) primary key,ZAKAT_AMT number(9),TOTAL_PAY number(9),SUBMISSION_DATE date());
commit;
create table MO_HEALTH(HOSP_ID number(9) primary key,HOSPITAL_NAME varchar(30),HOSP_REGION varchar(30));
commit;
create table EDUCATION(INSTITUTE_ID number(9) primary key,CLASS varchar(2),INSTITUTE_NAME date());
commit;
create table TRANSPORT(VEHICLE_NO varchar(9) primary key,TYPE varchar(1),AMD_DATE date());
commit;
create table OBEYS(CLAU_NO number(9),EMP_ID number(9));
commit;
create table USES(ACCOD_ID number(9),EMP_ID number(9));
commit;
create table GETS(EMP_ID number(9),INSTITUTE_ID number(9));
commit;
create table TRAVEL(EMP_ID number(9),VEHICLE_NO varchar(9));
commit;
alter table OBEYS add constraint ml_em_fk foreign key(EMP_ID) references MO_AGRICULTURE(EMP_ID));
commit;
alter table OBEYS add constraint em_ml_fk foreign key(CLAU_NO) references MO_LAW(CLAU_NO));
commit;
alter table USES add constraint acod_agri_fk foreign key(ACCOD_ID) references ACCOMODATION(ACCOD_ID));
commit;
alter table USES add constraint agri_acod_fk foreign key(EMP_ID) references MO_AGRICULTURE(EMP_ID));
commit;
alter table GETS add constraint agri_edu_fk foreign key(EMP_ID) references MO_AGRICULTURE(EMP_ID));
commit;
alter table GETS add constraint edu_agri_fk foreign key(INSTITUTE_ID) references EDUCATION(INSTITUTE_ID));
commit;
alter table TRAVEL add constraint agri_tran_fk foreign key(EMP_ID) references MO_AGRICULTURE(EMP_ID));
commit;
alter table TRAVEL add constraint tran_agri_fk foreign key(VEHICLE_NO) references TRANSPORT(VEHICLE_NO));